export const URL = 'http://localhost:3000/api/v1/'
export const USERS_URL = URL + 'users/'
export const FIND_MATCHES = URL + 'find_matches/'
export const DISABILITIES_URL = URL + 'disabilities/'
export const INTERESTS_URL = URL + 'interests/'
export const ADD_CARETAKER =  URL + 'caretaker_request/'
export const REMOVE_CARETAKER = URL + 'caretaker_remove/'
export const AUTH_URL = URL + 'login/'