export const URL = 'http://localhost:3000/api/v1/'
export const USERS_URL = URL + 'users/'
export const FIND_MATCHES = URL + 'find_matches/'
export const DISABILITIES_URL = URL + 'disabilities/'
export const INTERESTS_URL = URL + 'interests/'